### ISSUE TITLE
isacc4 install error

### ISSUE THREAD

**Issue by huangl07** [Illumina/Isaac4#14]
my dear:

when I have already download the newest Isaac4:
`/mnt/ilustre/centos7users/dna/.env/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../lib/alignment/libisaac_alignment.a(MatchSelector.cpp.o): in function `void isaac::alignment::MatchSelector::parallelSelect<isaac::alignment::ClusterHashMatchFinder<isaac::reference::ReferenceHash<isaac::oligo::BasicKmerType<20u>, isaac::common::NumaAllocator<void, -2> >, 4u> >(isaac::alignment::matchFinder::TileClusterInfo&, std::vector<isaac::alignment::TemplateLengthStatistics, std::allocator<isaac::alignment::TemplateLengthStatistics> >&, isaac::flowcell::TileMetadata const&, isaac::alignment::ClusterHashMatchFinder<isaac::reference::ReferenceHash<isaac::oligo::BasicKmerType<20u>, isaac::common::NumaAllocator<void, -2> >, 4u> const&, isaac::alignment::BasicBclClusters<isaac::common::NumaAllocator<char, -2> > const&, isaac::alignment::matchSelector::FragmentStorage&)':
/mnt/ilustre/centos7users/dna/biosoft/Isaac4-master/src/c++/lib/alignment/MatchSelector.cpp:333: undefined reference to `void isaac::alignment::matchSelector::TemplateDetector::determineTemplateLengths<isaac::alignment::ClusterHashMatchFinder<isaac::reference::ReferenceHash<isaac::oligo::BasicKmerType<20u>, isaac::common::NumaAllocator<void, -2> >, 4u> >(isaac::flowcell::TileMetadata const&, std::vector<isaac::alignment::matchFinder::ClusterInfo, std::allocator<isaac::alignment::matchFinder::ClusterInfo> > const&, std::vector<isaac::alignment::RestOfGenomeCorrection, std::allocator<isaac::alignment::RestOfGenomeCorrection> > const&, isaac::alignment::ClusterHashMatchFinder<isaac::reference::ReferenceHash<isaac::oligo::BasicKmerType<20u>, isaac::common::NumaAllocator<void, -2> >, 4u> const&, isaac::alignment::BasicBclClusters<isaac::common::NumaAllocator<char, -2> > const&, std::vector<isaac::alignment::TemplateLengthStatistics, std::allocator<isaac::alignment::TemplateLengthStatistics> >&, isaac::alignment::matchSelector::MatchSelectorStats&)'`

How could I do? thankyou!

**Comment by rpetrovski** [comment]
Just double-checked latest from master. Compiles and links without issues. Please check your environment and/or start over.

**Comment by huangl07** [comment]
well I have no ID where could I do

my Environment is gcc8.2，how could I check my environment?

**Comment by rpetrovski** [comment]
I would try a different box or, if on centos, play with toolset:
https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/

R.
