### ISSUE TITLE
GIFs are not generated

### ISSUE THREAD

**Issue by BenoitFiset** [Illumina/Isaac4#5]
Hi Roman,

  I can't get the GIF to be generated for the reports even with gnuplot loaded... tried 4.6 and 5.1 using the option  --stats-image-format gif.

Any tips ?

Thanks

**Comment by rpetrovski** [comment]
@BenoitFiset , you need to run from native illumina bcl, bcl-gz or bcl-bgzf in order to produce tile/cycle statistics plot.

Roman.

**Comment by BenoitFiset** [comment]
Hi,

  Figured out what was the issue... Had to use gnuplot 4.5 on my systems as the other versions didn't have the "GIF" terminal type.

In the logs:
set terminal gif medium size 747,600 
/Temp2/gnuplot-generate-images.dat", line 4: unknown or ambiguous terminal type; type just 'set terminal
' for a list
Dynamic exception type: boost::exception_detail::clone_impl<isaac::common::IsaacException>
std::exception::what: Couldn't execute the following command: gnuplot
