### ISSUE TITLE
ISAAC4 throws exceptions in fastqs with reads of different length

### ISSUE THREAD

**Issue by AndrewCarroll** [Illumina/Isaac4#6]
I am applying ISAAC4 to fastq files which contain reads of different lengths (the sequence length and quality string length still match). 

There are several valid reasons why reads within a FASTQ would have different lengths (for example read trimming). Should I not be encountering this error or is this an expected behavior for ISAAC4? Would support for reads of different lengths within a file be a supported use case in the future?

**Comment by rpetrovski** [comment]
Isaac needs to assume a certain read length to do the processing. It cannot autodetect it if the reads in fastq are not consistent. If you specify read length(s) with --use-bases-mask, it will truncate the reads from fastq that are longer and pad with Ns those that are shorter. If your data comes from the Illumina instrument, just set it to the cycle numbers used for the run. For example --use-bases-mask Y150,Y150 indicates paired run 2x150.

Roman.

**Comment by AndrewCarroll** [comment]
Ok, this seems to work. I am certain that many users will at some point encounter this if they are working with diverse datasets. But those who work directly with the output of full single runs and who don't use read trimmers will probably never encounter the issue. It's certainly not a major issue given that this workaround exists.
