### ISSUE TITLE
MARKDOWN_EXECUTABLE-NOTFOUND

### ISSUE THREAD

**Issue by asabaini** [Illumina/Isaac4#7]
As stated in the [install file](https://github.com/Illumina/Isaac4/blob/master/src/INSTALL#L22) `src/INSTALL`

```
Prerequisites:
--------------
- markdown tool will be used if available to generate html user manual
```
So I'm guessing that if it is not available, nothing will be generated. I have no markdown tool installed, and I'm not interested in having html user manual. When I run configure, however, I get this error.
```
gcc --version
gcc (GCC) 6.3.0
cmake --version
cmake version 3.10.1
../src/configure --prefix=/apps/isaac/4 --with-cmake=$(which cmake) --build-type=MinSizeRel
...
-- Could NOT find Markdown (missing: MARKDOWN_EXECUTABLE)
-- Markdown: MARKDOWN_EXECUTABLE-NOTFOUND.
```

Is there a flag I'm missing for `configure` for disabling build markdown docs?

**Comment by rpetrovski** [comment]
That is just a warning. You should be ok to proceed with make step.

**Comment by asabaini** [comment]
Yes indeed I was mislead by that being the last thing in the log before failure. Apparently in the error log I see a more worrisome `/usr/bin/ld: cannot find -lpthreads`, so I think it might be that causing the error. Sorry about that
