### ISSUE TITLE
Isaac can't configure project

### ISSUE THREAD

**Issue by asabaini** [Illumina/Isaac4#8]
Dear all,
I'm trying to build the project by following the instruction listed in src/INSTALL. Here are some details regarding my attempt (Boost 1.66, 
```
[asabaini@node001 Isaac-build]$ gcc --version
gcc (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
[asabaini@node001 Isaac-build]$ cmake --version
cmake version 3.11.0
[asabaini@node001 Isaac-build]$ ccache --version
ccache version 3.4.2
[asabaini@node001 Isaac-build]$ ../src/configure --prefix=/cm/shared/apps/isaac/4 --with-cmake=$(which cmake) --build-type=MinSizeRel --without-numa --without-unit-tests
```
Salient parts of the log are
```
...
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
...
-- Could NOT find LibXml2: Found unsuitable version "2.9.1", but required is at least "2.9.6" (found /usr/lib64/libxml2.so)
-- Could NOT find LibXslt: Found unsuitable version "1.1.28", but required is at least "1.1.31" (found /usr/lib/libxslt.so)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- Checking for module 'libexslt'
--   No package 'libexslt' found
-- Found LibExslt: /usr/lib/libexslt.so (Required is at least version "0.8.19")
...
-- Successfuly unpacked /local/Isaac4-Isaac-04.18.01.19/src/../redist/libxml2-2.9.6.tar.gz from the distribution package...
    configuring LIBXML2
-- Successfuly configured libxml2-2.9.6 from the distribution package...
    installing LIBXML2
-- Successfuly built libxml2-2.9.6 from the distribution package...
-- Find library redist , HINTS /local/Isaac4-Isaac-04.18.01.19/Isaac-build/bootstrap/lib: /usr/lib64/libxml2.so
-- Found redist LIBXML2  header: /local/Isaac4-Isaac-04.18.01.19/Isaac-build/bootstrap/include/libxml2/libxml/xpath.h
-- Found redist LIBXML2 library: /usr/lib64/libxml2.so
    unpacking (/local/Isaac4-Isaac-04.18.01.19/src/../redist/libxslt-1.1.31.tar.gz)
-- Successfuly unpacked /local/Isaac4-Isaac-04.18.01.19/src/../redist/libxslt-1.1.31.tar.gz from the distribution package...
    configuring LIBXSLT
-- Successfuly configured libxslt-1.1.31 from the distribution package...
    installing LIBXSLT
...
-- Configuring incomplete, errors occurred!
See also "/local/Isaac4-Isaac-04.18.01.19/Isaac-build/CMakeFiles/CMakeOutput.log".
See also "/local/Isaac4-Isaac-04.18.01.19/Isaac-build/CMakeFiles/CMakeError.log".
Couldn't configure the project:
```
Attached you can find the complete logs. I can't really see what error is causing this issue. Can you please help me?
[CMakeError.log](https://github.com/Illumina/Isaac4/files/1906625/CMakeError.log)
[CMakeOutput.log](https://github.com/Illumina/Isaac4/files/1906626/CMakeOutput.log)

Thank you in advance
Alberto

**Comment by rpetrovski** [comment]
pthread is not an issue. Can you please include the entire configure output.

Roman.

**Comment by asabaini** [comment]
Dear Roman
thank you for your quick response, I attached to this comment the entire configure output. 

Thanks
Alberto
[configure-out.log](https://github.com/Illumina/Isaac4/files/1906734/configure-out.log)

**Comment by rpetrovski** [comment]
Below is the output of configure when I run it. It is mostly similar to yours (apart from installing boost in my case). The main difference that I see is that your output seems to be missing the steps of installing libxml and libxslt. Also, in your case it finds libxlt in /usr/lib and not /usr/lib64. Would you be able to remove libxml2-devel package to reduce the confusion? 

Which distro are you using btw?

boost-1_62_0 installed successfully
-- Successfuly built boost 1.62.0 from the distribution package...
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- inttypes.h found as 1
-- Looking for malloc.h
-- Looking for malloc.h - found
-- malloc.h found as 1
-- Looking for memory.h
-- Looking for memory.h - found
-- memory.h found as 1
-- Looking for signal.h
-- Looking for signal.h - found
-- signal.h found as 1
-- stdint.h found as 1
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- stdlib.h found as 1
-- Looking for string.h
-- Looking for string.h - found
-- string.h found as 1
-- Looking for time.h
-- Looking for time.h - found
-- time.h found as 1
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- sys/stat.h found as 1
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for linux/falloc.h
-- Looking for linux/falloc.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - found
-- Looking for fallocate
-- Looking for fallocate - found
-- Looking for floorf
-- Looking for floorf - found
-- Looking for round
-- Looking for round - found
-- Looking for roundf
-- Looking for roundf - found
-- Looking for powf
-- Looking for powf - found
-- Looking for erf
-- Looking for erf - found
-- Looking for erf
-- Looking for erf - found
-- Looking for erfc
-- Looking for erfc - found
-- Looking for erfc
-- Looking for erfc - found
-- Looking for stat
-- Looking for stat - found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for clock
-- Looking for clock - found
-- Looking for zlib.h
-- Looking for zlib.h - found
-- Checking library: z
-- Found ZLIB  header: 1/zlib.h
-- Found ZLIB library: /usr/lib64/libz.so
-- gzip compression supported
-- Looking for time.h
-- Looking for time.h - found
-- Checking library: rt
-- Found RT  header: 1/time.h
-- Found RT library: /usr/lib64/librt.so
-- adding librt dependency to support clock_gettime linking on legacy platforms
-- Looking for cppunit/config-auto.h
-- Looking for cppunit/config-auto.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Checking library: pthread
-- Found PTHREAD  header: 1/pthread.h
-- Found PTHREAD library: /usr/lib64/libpthread.so
-- pthread supported
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   iostreams
--   program_options
--   regex
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Could NOT find LibXml2: Found unsuitable version "2.9.1", but required is at least "2.9.6" (found /usr/lib64/libxml2.so)
-- Could NOT find LibXslt: Found unsuitable version "1.1.28", but required is at least "1.1.31" (found /usr/lib64/libxslt.so)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- Checking for module 'libexslt'
--   Found libexslt, version 0.8.17
-- Found LibExslt: /usr/lib64/libexslt.so (Required is at least version "0.8.19")
 Not found: LibExslt, incorrect version (  )
    unpacking (/export/ssd/rpetrovski/workspacer/iSAAC-04/src/../redist/libxml2-2.9.6.tar.gz)
-- Successfuly unpacked /export/ssd/rpetrovski/workspacer/iSAAC-04/src/../redist/libxml2-2.9.6.tar.gz from the distribution package...
    configuring LIBXML2
-- Successfuly configured libxml2-2.9.6 from the distribution package...
    installing LIBXML2
-- Successfuly built libxml2-2.9.6 from the distribution package...
-- Find library redist , HINTS /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/lib: /usr/lib64/libxml2.so
-- Found redist LIBXML2  header: /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/include/libxml2/libxml/xpath.h
-- Found redist LIBXML2 library: /usr/lib64/libxml2.so
    unpacking (/export/ssd/rpetrovski/workspacer/iSAAC-04/src/../redist/libxslt-1.1.31.tar.gz)
-- Successfuly unpacked /export/ssd/rpetrovski/workspacer/iSAAC-04/src/../redist/libxslt-1.1.31.tar.gz from the distribution package...
    configuring LIBXSLT
-- Successfuly configured libxslt-1.1.31 from the distribution package...
    installing LIBXSLT
-- Successfuly built libxslt-1.1.31 from the distribution package...
-- Find library redist , HINTS /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/lib: /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/lib/libexslt.a
-- Found redist LIBEXSLT  header: /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/include/libexslt/exslt.h
-- Found redist LIBEXSLT library:
-- Find library redist , HINTS /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/lib: /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/lib/libxslt.a
-- Found redist LIBXSLT  header: /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/bootstrap/include/libxslt/xsltconfig.h
-- Found redist LIBXSLT library:
-- using compiler: gcc version 7
-- Found ccache: /usr/bin/ccache
-- Adding the c++    library subdirectory: bgzf
-- Adding the c++    library subdirectory: common
-- Adding the c++    library subdirectory: oligo
-- Adding the c++    library subdirectory: io
-- Adding the c++    library subdirectory: rta
-- Adding the c++    library subdirectory: flowcell
-- Adding the c++    library subdirectory: demultiplexing
-- Adding the c++    library subdirectory: xml
-- Adding the c++    library subdirectory: reference
-- Adding the c++    library subdirectory: bam
-- Adding the c++    library subdirectory: options
-- Adding the c++    library subdirectory: statistics
-- Adding the c++    library subdirectory: alignment
-- Adding the c++    library subdirectory: build
-- Adding the c++    library subdirectory: package
-- Adding the c++    library subdirectory: reports
-- Adding the c++    library subdirectory: workflow
-- Adding the c++    program subdirectory: bin
-- Adding the c++    program subdirectory: libexec
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen dot
-- Doxygen: /usr/bin/doxygen. Dot: /usr/bin/dot.
-- Creating Doxygen config file: /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72/c++/Doxyfile
-- Could NOT find Markdown (missing: MARKDOWN_EXECUTABLE)
-- Markdown: MARKDOWN_EXECUTABLE-NOTFOUND.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    iSAAC_DOCDIR
    iSAAC_INCLUDEDIR
    iSAAC_MANDIR


-- Build files have been written to: /export/ssd/rpetrovski/workspacer/build/iSAAC-04-gcc72

**Comment by asabaini** [comment]
I'm on Centos 7, sorry for leaving that detail out. I removed libxml2-devel and run again `../src/configure --prefix=/cm/shared/apps/isaac/4 --with-cmake=$(which cmake) --build-type=MinSizeRel --without-numa --without-unit-tests`.

```
...
-- Configuring done
-- Generating done
```
By removing that library libxml2-devel, everything worked smoothly with the configure. I ran make it had problem linking a library at 96% of make process, see attached file
[make-error.log](https://github.com/Illumina/Isaac4/files/1907405/make-error.log)

I ran configure without selecting my boost module, make and make install were successful :)  Thank you for the help. I live the issue open in case you need to ask some follow up questions. Otherwise we can close it

thanks

**Comment by rpetrovski** [comment]
Yeah, 3-rd party boost installations are known to confuse Isaac. Thank you for the info!

Roman.
