### ISSUE TITLE
about version 04.17.06.15

### ISSUE THREAD

**Issue by mortunco** [Illumina/Isaac4#9]
Hi, 

We are investigating multiple WGS tumor samples. From three projects we have three different pipelines. To be able to compare apples and apples, could you help me to find Isaac aligner version 04.17.06.15. It was used in project that we cannot realy have the fastqs. So that we have to map the remaining samples with this version to make unbiased comparison.

Thank you very much for the help,

Best regards,

Tunc.

**Comment by rpetrovski** [comment]
https://github.com/Illumina/Isaac4/tree/Isaac-04.17.06.15
If you open up the  branch an then go to tags tab, you should see it. Every git hub code drop is tagged. Cheers. 

Roman.

**Comment by mortunco** [comment]
Oh. Sorry.

Thank you very much!!
